@startuml control
start
:Inicializar variables (Ganancias);
:Inicializar ROS;
:Inicializar motores a 1450 ms de PWM;
repeat : Suscribirse a nodo "/Coordinates";
  :Calcular errores;
  :Calcular la suma de los errores;
  :Obtener valores de ganancias Kp, Ki;
  :Calcular PI;
  :Convertir PI a valor de PWM;
  (A)
  detach
  (B)
repeat while (ROS == ok)
stop
@enduml