@startuml publisher
start
partition ROS_Init {
	:Creamos nodo;
	:Creamos objeto de la clase ImageTransport;
    :Obtenemos parametros;
    :Creamos el Topic;
    
}
partition OpenCV {
	:Creamos objeto de la clase VideoCapture;
    :Abrimos el COM de la camara;
    if (COM abierto?) then (si)
      :Creamos un frame tipo Mat;
    else (no)
      :Return 1;
    stop
    endif

}
partition ROS_Publisher {
    :Creamos objeto de la clase ImagePtr;
    :Establecemos tiempo de muestreo;
    while (Nodo de ROS vivo?) is (si)
      :Obtenemos frame de camara;
      :convertimos frame a mensaje tipo CvImage;
      :Codificamos la imagen a 8bits;
      :Publicamos frame;
    endwhile (no)
    :return 0;
}

stop
@enduml